// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhh2WIO4tAlH5xJjtRHCdVSk6OwKcOkbU',
    appId: '1:263211408457:web:7b9b85449b9e980661b398',
    messagingSenderId: '263211408457',
    projectId: 'app-mantenimiento-95ba2',
    authDomain: 'app-mantenimiento-95ba2.firebaseapp.com',
    storageBucket: 'app-mantenimiento-95ba2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqe-y-Id5d0OpthbrU0r-80YpoFekTb2U',
    appId: '1:263211408457:android:8f02ab1b2d1731bd61b398',
    messagingSenderId: '263211408457',
    projectId: 'app-mantenimiento-95ba2',
    storageBucket: 'app-mantenimiento-95ba2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0KzUd33AVknanZ9y8OAAEXwscn4DqcV8',
    appId: '1:263211408457:ios:7a9306a105a97d7761b398',
    messagingSenderId: '263211408457',
    projectId: 'app-mantenimiento-95ba2',
    storageBucket: 'app-mantenimiento-95ba2.firebasestorage.app',
    iosBundleId: 'com.example.AppMant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0KzUd33AVknanZ9y8OAAEXwscn4DqcV8',
    appId: '1:263211408457:ios:87ac2b3344a505ea61b398',
    messagingSenderId: '263211408457',
    projectId: 'app-mantenimiento-95ba2',
    storageBucket: 'app-mantenimiento-95ba2.firebasestorage.app',
    iosBundleId: 'com.example.AppMant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhh2WIO4tAlH5xJjtRHCdVSk6OwKcOkbU',
    appId: '1:263211408457:web:ca234460461b5ed861b398',
    messagingSenderId: '263211408457',
    projectId: 'app-mantenimiento-95ba2',
    authDomain: 'app-mantenimiento-95ba2.firebaseapp.com',
    storageBucket: 'app-mantenimiento-95ba2.firebasestorage.app',
  );

}